### PR TITLE
Create RoboCommandParser.cs

### PR DESCRIPTION
**Pull request by RFBomb**
This is in reference to #187. This creates a factory object to produce IRoboCommand objects based on an input string such as `robocopy "source" "destination"  /mirror`.

ToDo:
 - Unit tests
 - Higher level logic such as included/excluded files
 - testing extraction of parameters like the Min/Max file age.

### CODE REVIEW

**Comment by RFBomb** [comment]
Regex to implement for exclusion parsing:

(?<F>/XF\s+((("[\w\-.*\s]+")|([\w\-*.]+))\s*)+)


(?<xd>/XD\s*
((
(“[\w\\\/$:\-\s]+”) |
((//[a-zA-Z]|[A-Z]:|[^/])([\w\\\/$:]+))
)\s*)+)

**Comment by RFBomb** [comment]
This is now functional and ready for review/merge.  
@PCAssistSoftware  

I believe I've covered all of the options currently provided. Its a lot, so a second set of eyes would be nice. The main file to review is RoboCommandParser.cs, as its the one that has all the instructions for parsing. The other functions are in the ROboCommandParserFunctions.cs, which are all unit tested, so my only real concern is that I forgot to check for an option.

**Comment by PCAssistSoftware** [comment]
Nice one, will try and find sometime this coming week to look over the code and run some tests, hopefully @LordPinhead will also check it out and comment

**Comment by PCAssistSoftware** [comment]
Okay found a few minutes to do some initial testing

Obviously other than just following the PR updates I haven't really looked into the code etc, so my first test was simply based upon using a robocopy.exe command I had recently used so I used the following.  At this point I obviously didn't know if you were expecting to just provide the switches / commands or the whole command, so I included robocopy.exe as well.

`Dim c = RoboCommandParser.Parse("robocopy.exe \\pc-01\c$\SoftwareLib\LegacySoftware C:\test /E /ZB /MIR /MT:128")`

This didn't work

So I tried it again with just robocopy rather than robocopy.exe and this worked perfectly :)

`Dim c = RoboCommandParser.Parse("robocopy \\pc-01\c$\SoftwareLib\LegacySoftware C:\test /E /ZB /MIR /MT:128")`

as did the below where I just provided the commands.

`Dim c = RoboCommandParser.Parse("\\pc-01\c$\SoftwareLib\LegacySoftware C:\test /E /ZB /MIR /MT:128")`

So might be worth covering all basis in case the provided string includes Robocopy.exe perhaps?

Hope that makes sense.

**Comment by PCAssistSoftware** [comment]
More complex command worked fine 

`Dim c = RoboCommandParser.Parse("C:\source\folder\path\ D:\destination\folder\path\ /E /Z /ZB /R:5 /W:5 /TBD /NP /V /XD ""C:\source\folder\path\to\exclude folder""")`

BUT if you have spaces in source and/or destination path then it doesn't work e.g.

` Dim d = RoboCommandParser.Parse("C:\source\folder\path one\ D:\destination\folder\path two\ /E /Z /ZB /R:5 /W:5 /TBD /NP /V /XD ""C:\source\folder\path\to\exclude folder""")`

**Comment by LordPinhead** [comment]
Oh I will check this one out this week and give it a try. Because we use ETCD for such jobs, I have a config entry for the parameters, so I just need them parsed atm. But if I can use the whole line, it's ok too. As long as my co-workers can build jobs on my middleware, I'm happy with it :)

**Comment by PCAssistSoftware** [comment]
Need to be careful with switches such as /NJS /NFL /NDL - which yes it parses okay, but if set to true then going on my previous notes would break apps using RoboSharp e.g. /NFL set to true would break displaying of file progress or file name in your GUI. /NDL breaks logging as doesn't then contain full information and finally and more importantly I believe if /NJS is set to true it breaks statistics completely

**Comment by RFBomb** [comment]
That's a good point about 'robocopy.exe' vs 'robocopy', and is an easy thing to incorporate. I'll even take a look at accommodating paths such as 'D:/robocopy.exe'


I was hesitant about some of the other switches that I'm aware of breaking RoboSharp, BUT those switches are still provided by the library, so I took the position of it's no different than if they set the flag in code, even if it does break things like statistics. I'm simply parsing into an equivalent command.

**Comment by RFBomb** [comment]
Does robocopy actually accept that command with spaced and non-quoted source/destination? Everything I can find says that quotes are required for paths with spaces.

`C:\source\folder\path one\`
`D:\destination\folder\path two\`


Should be 

`"C:\source\folder\path one"`
`"D:\destination\folder\path two"`

**Comment by LordPinhead** [comment]
Pretty much yes, every space marks the end of a command argument in any commandline or shell system

**Comment by RFBomb** [comment]
> /NJS is set to true it breaks statistics completely

This used to be the case, but with my implementation of ProgressEstimator, it can still report something (assuming PE doesn't break due to other switches being set)

**Comment by PCAssistSoftware** [comment]
> I was hesitant about some of the other switches that I'm aware of breaking RoboSharp, BUT those switches are still provided by the library, so I took the position of it's no different than if they set the flag in code, even if it does break things like statistics. I'm simply parsing into an equivalent command.

Fair point

**Comment by PCAssistSoftware** [comment]
> > /NJS is set to true it breaks statistics completely
> 
> This used to be the case, but with my implementation of ProgressEstimator, it can still report something (assuming PE doesn't break due to other switches being set)

Oh okay, I hadn't actually tested it yet, was just looking at the parsing for each switch and comparing with my notes and noted I had put a warning about /NJS from the past

**Comment by PCAssistSoftware** [comment]
> Does robocopy actually accept that command with spaced and non-quoted source/destination? Everything I can find says that quotes are required for paths with spaces.
> 
> `C:\source\folder\path one\` `D:\destination\folder\path two\`
> 
> Should be
> 
> `"C:\source\folder\path one"` `"D:\destination\folder\path two"`

Good point, no it doesn't - but perhaps would be good to have some sort of error handling so if someone did try and parse an invalid string like that it just fails rather than producing wrong commands? just an idea

**Comment by RFBomb** [comment]
> perhaps would be good to have some sort of error handling so if someone did try and parse an invalid string like that it just fails rather than producing wrong commands?

Not opposed to that.
We would have to somewhat strictly define the requirements then of when an exception will throw.  For example, should we require a source/destination? Should we require it begins with 'robocopy' ? What about paths to a specific robocopy? 

`robocopy C:\Some Dir\ D:\SomeDestination`

Would result in a command with source `C:\Some`, destination `Dir\` and file inclusion `D:\SomeDestination`

Obviously right now we can tell that's invalid. But for throwing errors, how do we validate against that? Ensuring that if a source/destination were parsed that both are fully qualified?  If they are not found at all, is that an error?

**Comment by PCAssistSoftware** [comment]
Yes that is a bit more of an awkward one and I suspect not everyone would have the same opinion?

Personally I think it should require that it includes a source / destination
What it begins with should if possible cover a) starting with robocopy, b) starting with robocopy.exe, c) starting without a or b and just starting with source first e.g.

a) robocopy "C:\Some Source\" "D:\SomeDestination"
b) robocopy.exe "C:\Some Source\" "D:\SomeDestination"
c) "C:\Some Source\" "D:\SomeDestination"

**Comment by LordPinhead** [comment]
When you parse the string and the argument you find is not starting with a / , that should work as a check.
i.e. c:\temp\My Documents k:\test
It would be "Source" -> c:\temp\my " destination "Documents" and the first "argument is "k:\test", so it's not starting with the / and should throw an error with the hint of quoting paths.

**Comment by RFBomb** [comment]
I can agree with your ABC examples. Robocopy also requires fully qualified source/destination. So if either path is not fully qualified, throw an error as such.

Robocopy syntax requires that any file filters immediately follow source/destination. There is no /switch for filters, only for exclusions. As such, I'm currently taking anything between the end of the destination and the first / as a file filter. Any thoughts on this aspect?

**Comment by PCAssistSoftware** [comment]
> I can agree with your ABC examples. Robocopy also requires fully qualified source/destination. So if either path is not fully qualified, throw an error as such.

agreed

> Robocopy syntax requires that any file filters immediately follow source/destination. There is no /switch for filters, only for exclusions. As such, I'm currently taking anything between the end of the destination and the first / as a file filter. Any thoughts on this aspect?

yes I agree anything following destination and before first / is a file.filter and this is optional as if you don't specify then RoboCopy just assumes *.*

**Comment by RFBomb** [comment]
The changes have been implemented for review.

**Comment by PCAssistSoftware** [comment]
So far testing going well and works as expected.

Still think we should not parse (or at least warn) for /NFL (LoggingOptions.NoFileList) as when set to true then areas such as showing progress of current file copying don't work correctly

EDIT: or perhaps some way of not including it for those of us who have designed apps which would break with it included - so it covers everyone's needs?

**Comment by RFBomb** [comment]
>Still think we should not parse (or at least warn) for /NFL (LoggingOptions.NoFileList) as when set to true then areas such as showing progress of current file copying don't work correctly 

Well, the options are:
A ) throw an error and stop the whole parsing
B ) Parse and Ignore (no feedback)
C ) Parse as is.

I'm still of the opinion for parse as is, and throw an error only if a major error occurred (such as missing source/destination). 

>or perhaps some way of not including it for those of us who have designed apps which would break with it included - so it covers everyone's needs

There is no rule stipulating that apps the utilize the library must rely on this parser to create commands. Even if they did, it would be up to that developer to ensure that they set up the command correctly for their particular use case. In your example, I would suggest: 

```
dim rc = RoboCommandParser.Parse(input);
rc.LoggingOptions.NoFileList = False;
```

Other consumers may not care about the file list, so to change their entire log for the benefit of something they may not be using doesn't seem correct to me. ( They may not be doing anything with the file list at all, simply using it to start/stop/cancel/track when a command completes )

**Comment by PCAssistSoftware** [comment]
ok

**Comment by RFBomb** [comment]
I have implemented the Parser into the example app so that concerns can be tested using that.

**Comment by PCAssistSoftware** [comment]
> I have implemented the Parser into the example app so that concerns can be tested using that.

Nice one :)

**Comment by RFBomb** [comment]
Updated again, this now has a `ParseOptions()`, `TryParse` and `TryParseOptions` method.
The ParseOptions methods is intended for use with a string of options that does not declare a source/destination. If a source/destination are declared, it will cause an exception. 

This has also been implemented into the example app for testing. I believe this now satisfies all potential uses.

**Comment by PCAssistSoftware** [comment]
> Updated again, this now has a `ParseOptions()`, `TryParse` and `TryParseOptions` method. The ParseOptions methods is intended for use with a string of options that does not declare a source/destination. If a source/destination are declared, it will cause an exception.
> 
> This has also been implemented into the example app for testing. I believe this now satisfies all potential uses.

Yes I noticed the commit and had then been trying it out in the example app - great work (as always!)

**Comment by PCAssistSoftware** [comment]
All working fine from what I have tested, will just wait for @LordPinhead to test / comment and then if all happy can merge

**Comment by PCAssistSoftware** [comment]
@LordPinhead - Hi, could you test this when you get a moment and confirm it works okay for your needs as well? Then I can get it merged in and released.  Thanks

**Comment by LordPinhead** [comment]
I try to test it this week, we are crunchtiming atm with a release of our main ERP and I have severe bugs in our Nextcloud update. I try to get 10 minutes for a test with our example.

**Comment by RFBomb** [comment]
I will be making a tiny change to the new Default RoboCommand factory this morning to return the interface instead of the typed object for a bit more protection. (Prevent consumers messing with the default factory settings, if they want to customize the settings they can instantiate their own instance of the factory)

edit: done

**Comment by LordPinhead** [comment]
I finally had time to change my project to your version. When I tested it, the path had "robocopy" in it, but I did not add the "robocopy" to the start or the string, so it threw me an exception. I added the robocopy to the string, it still threw me an exception. Optionally, the check in TrimRocopy should check if the string starts with robocopy and not in the path, that´s why I split the arguments and paths. When somebody has has robocopy in his destination path, this would be a problem (I remember a coworker that had this). For me, it was just in a local test.

Otherwise, it works like a charm :) Thx for the work,

**Comment by PCAssistSoftware** [comment]
@LordPinhead - thanks for testing

@RFBomb  - yes I can replicate the scenario that LordPinhead mentions and also get an error e.g.

 `Dim x = RoboCommandParser.Parse("robocopy.exe d:\SoftwareLib\RoboCopyTest C:\test /E /ZB /MIR /MT:128")`

image

**Comment by LordPinhead** [comment]
Also, would single quoted paths work in CMD? I have to check that, I think it´s working but it´s not working with the parser.

**Comment by RFBomb** [comment]
Adding in single-quoted paths is possible, but unfortunately I just tested it out, you can create a new folder whose name is a single quote : `'`. 
If the desire is there, we can try to patch it in, but given its a valid character in a file/folder name, whereas double quotes are not, I think sticking to double quotes is the better standard.

I had not considered someone having a path with the name 'robocopy' in it when I wrote that bit of code .

edit: A workaround is still likely needed for that issue. 
` d:\robocopy` will execute the file `d:\robocopy.exe` if it exists. that was the reason I was throwing the error 
Now, if you pass in the following : 
`c:\myfolder\robocopy d:\mydestination` it will still error out, but this time with an unable to parse source/destination error. This is because `c:\myfolder\robocopy` could start the process via command prompt, so it has to be treated as such. 

workaround: either put 'robocopy' at the start of the input text. OR ensure that the source/destination paths end in a `\` character. 

ERRORS -- `c:\myfolder\robocopy d:\mydestination`
        OK -- `c:\myfolder\robocopy\ d:\mydestination`
        OK -- `robocopy c:\myfolder\robocopy d:\mydestination`

**Comment by RFBomb** [comment]
single quotes do not work on cmd - they are treated as a filename. In this case, it assumed I had a folder path of `c:\'c:\rst'\` when my inputs was `'c:\rst'`

image

**Comment by PCAssistSoftware** [comment]
Thanks @RFBomb - I totally agree with all your logic above, and have tested your changes and all works for me.  If @LordPinhead you could test and comment then if we are all happy I will merge this PR in

**Comment by LordPinhead** [comment]
@PCAssistSoftware  I´m happy, you can merge it, I like the implementation. A big thanks @RFBomb :)

**Comment by PCAssistSoftware** [comment]
@LordPinhead - thanks for that

@RFBomb - just checking you don't want to change anything else, if not I will merge it :)

**Comment by PCAssistSoftware** [comment]
Hi @RFBomb 

Found an issue if parsing a command line which has no source / destination then it seems to ignore the file filter supplied e.g.

Dim w = RoboCommandParser.Parse("""" *.docx /E")
      Dim x = RoboCommandParser.Parse(""""" """" *.docx /E")
      Dim y = RoboCommandParser.Parse("robocopy.exe """" *.docx /E")
      Dim z = RoboCommandParser.Parse("robocopy """" """" *.docx /E")

Whether I use "" or "" "" for blank source / destination it still ignores the *.docx for file filter

Any thoughts please

**Comment by RFBomb** [comment]
ParseOptions should work if you know that there is no source/destination in the string. 

Otherwise we can double check it with some unit tests. Some tests should already be set up for that, but I'll review it

**Comment by PCAssistSoftware** [comment]
Hadn't tried ParseOptions, as in my app I wanted user to be able to enter a whole command either with or without source / destination, so app wouldn't know until parsing it that no source / destination had been supplied e.g. using "" instead.

Thank you

**Pull request merged**
