### PR TITLE
Add Robocopy error codes to error events 

### PR DESCRIPTION
**Pull request by bernatpi**
This pull request adds the error code displayed on robocopy's output to `OnError` event args and robocopy exit code to `OnComandCompleted` event args, fixing issue #33.

### CODE REVIEW

**Comment by wingers999** [comment]
For info this pull request which seems to have been ignored handled exit codes and also provided access to lots of other useful copy stats - have used it in my build for a long time now and it works well - might be worth making use of some of that as well as you seem to have more luck than he did in getting it merged! - https://github.com/tjscience/RoboSharp/pull/40

**Comment by bernatpi** [comment]
Thanks, it's definitely worth a look. At first glance, the parsing of the statistics is language dependent, but I think there's an easy fix. Also, I think that I know how to handle the cancelation of large files and the addition of speed results.

Do you know how to handle this changes? I mean, I don't know if/how I can contribute code to the existing pull request (#40) and hopefully get it merged, or if I need to open a new one against the `dev` branch. I'm pretty new to GitHub :-)

**Comment by wingers999** [comment]
I manually merged the changes into my build a long time ago and the statistics work so well as it allows me to run Robocopy with /l switch e.g. list only so I can then see what files / folders have changed and then either show message to use asking if they wish to continue or to say no changes found etc.  Also allows me to add stats to end of log / report in same way standard robocopy command line does.

Not totally sure, think you would be better opening a new pull request as no point contributing to #40 as it has been on here for 2 years now and been ignored.

Would be great if you can do it - let me know, always happy to do any testing etc

**Comment by tjscience** [comment]
Hi All. Thanks for your work on the project. As you have both contributed and continue to contribute to RoboSharp, would you be willing to become contributors? 

Regarding #40, I did take a look at that pull way back when and there were conflicts that needed to be resolved which were preventing me from merging.

**Comment by wingers999** [comment]
Hi, always glad to help, you project has been of great use to me, so like to give back when I can.  Yes that would be good.

Regarding #40 I had manually combined it with my offline version and the only file that conflicted was the csproj, all other code changes worked fine and do really add a lot to the project in my opinion

**Comment by wingers999** [comment]
Further to my point about #40 - it is definitely worth merging or even making the changes manually if that is the only way - the benefits it gives are well worth it.  I made my own GUI to work with it, but it allowed me to use the statistics along with / l (LoggingOptions.ListOnly) to be able to compare source and destination and give user a choice, and then also to have more details in a log when completed .  See screenshots attached

My fork (https://github.com/wingers999/RoboSharp) contains the changes from #40 along with #68 and #80 along with some misc fixes and changes to .NET version required

robo1
robo2

**Comment by tjscience** [comment]
@wingers999, as you are now a contributor, please feel free to merge pulls if they benefit RoboSharp. Thanks!

**Comment by bernatpi** [comment]
Hi @tjscience. This project has also been very useful to me and I'm very grateful for your work. Nowadays I try to contribute whenever I can, so yes, it would be a pleasure if it's OK with you.

On to the discussion, I also think that #40 is worth merging, but as said earlier there's the cancellation issue, the language dependent parsing and the speed results, which I will be working on it as soon as possible. Maybe we should merge #40 onto `dev` and work from there, as this way we won't have to copy code from one commit to another.

**Comment by wingers999** [comment]
@bernatpi - perhaps we could clone my fork to a new dev as that already contains your file filter fix from #80 along with #40 and #68 ? just an idea, would make a good base for you to then look at sorting the cancellation issue, parsing and speed resutls etc perhaps?

**Comment by bernatpi** [comment]
Yes, that would be great. This way I can work more easily on other open issues and merge them to the current dev. Thank you.

**Comment by wingers999** [comment]
Now all I need to do is work out how to clone from one to another....

**Comment by bernatpi** [comment]
I don't know if/how you can create a new branch, but maybe it's cleaner if you create a pull request from your branch to the current `dev` and then we can both work on that pull request until it's ready to merge.

**Comment by wingers999** [comment]
Hopefully now done

**Comment by bernatpi** [comment]
I already merged the current `dev` to #82 and resolved the merge conflicts, so we can work from there. If it's OK to you I will accept this pull request, there are changes in here that I will use in #82.

**Comment by wingers999** [comment]
Yes that makes sense to me

**Pull request merged**
