### PR TITLE
Extended results

### PR DESCRIPTION
**Pull request by alex-becker-startp**
Adds a new method GetResults() to CopyCommand.
The returned class provides acecss to the exit code of robocopy and some copy statistics.

### CODE REVIEW

**Comment by wingers999** [comment]
Hi alex

Really love the extended results idea and have implemented it in my fork

Just curious as to what the best way is to then access the statistics in my form so I can show the results on screen when copy completed?

**Comment by alex-becker-startp** [comment]
Hi wingers999,

just call GetResults() on the RoboCommand instance when Start() completed.
To display the results you could for example bind the properties of the RoboCopyResults instance to WPF elements.

Unfortunately you cannot relay on the Results property of the RoboCommandCompletedEvent arguments because I forgot to set the property in the constructor of this class.
Maybe you can add this line and commit this fix, because I have very limited knowledge in using GIT...

**Comment by wingers999** [comment]
Hi, thanks for reply.  In the end I changed the declaration from Private to Public at top of RoboCommand.cs - and then I could access results in my form in form of copy.results.BytesStatistic.Total etc

**Comment by wingers999** [comment]
P.S. Alex - If you tell me what line needs adding then I will add and commit the fix for you

**Comment by alex-becker-startp** [comment]
@wingers999 
this would be nice! 

in file RoboSharp/RoboCommandCompletedEventArgs.cs modify the constructor as following:
` 
public RoboCommandCompletedEventArgs(Results.RoboCopyResults results)
{
      this.Results = results;
  }
`

and in the solution file I forgot to remove the reference to my test project.
This caused the build error in the pull request...
This project reference needs to be removed from the .sln: RoboSharp.ConsoleTest.csproj

Alex

**Comment by wingers999** [comment]
1) I think you need to give me push access to be able to make a change?

2) Changing the code you mentioned gives lots of errors, so below not correct I don't think

using System;
using System.Security.Cryptography.X509Certificates;

namespace RoboSharp
{
    public class RoboCommandCompletedEventArgs : EventArgs
    {
        public RoboCommandCompletedEventArgs(Results.RoboCopyResults results) { this.Results = results; }
        {
        }

        public Results.RoboCopyResults Results { get; }
    }
}

3) yes if I get access I will sort the reference to test project as well


If not you can go to the page showing the changed files https://github.com/tjscience/RoboSharp/pull/40/files and click the little icon which looks like a pencil next to the relevant file to modify it

**Comment by alex-becker-startp** [comment]
@wingers999 

Hey, great, did not know about the online edit feature :-)
Now it seems to pass the build check!

**Comment by wingers999** [comment]
Fantastic - and I can confirm it now works perfectly for me!!!  Great work

**Comment by wingers999** [comment]
@alex-becker-startp 

Without changing at top of RoboCommand.cs

Private results As Results.RoboCopyResults
to
Public results As Results.RoboCopyResults

I still cannot work out how another way of accessing the results on my form

Changing it to Public works but concerned I should be doing something else

Please explain if you can

P.S. Hopefully your changes will get merged into the master project at some point - as very useful to have the stats etc

**Comment by wingers999** [comment]
@alex-becker-startp 

Something else I notice using these changes - if you start a copy and then click cancel you get an error about "object reference not set to an instance of an object"

Will let you know if I find cause and solution

**Comment by alex-becker-startp** [comment]
@wingers999 

okay, the intended usages are as following:

    var cmd = new RoboCommand();
    var results = await cmd.StartAsync();
    // do something with results...

or

    var cmd = new RoboCommand();
    var copyTask = cmd.Start();
    copyTask.Wait(); // be careful to avoid deadlocks here!
    var results = cmd.GetResults();
    // do something with results...

or

    var cmd = new RoboCommand();
    cmd.OnCommandCompleted += (args) => 
    {
        var results = args.Results;
        // do something with results...
    }
    cmd.Start();

Alexander

**Comment by wingers999** [comment]
@alex-becker-startp 

Thank you that is very useful

For the "object reference not set to an instance of an object" message when cancelling a copy part way through, it is coming from line 284 of RoboCommand.cs   

  results = resultsBuilder.BuildResults(process.ExitCode)

I have encased it in a try...catch for now and it works

Seems that when cancelling job no results or exitcode is available

**Comment by alex-becker-startp** [comment]
@wingers999 

my last fix should help you out with cancelled processes:

When the process was cancelled by .Stop() the GetResults().Status.ExitCodeValue will be set to -1 indicating that the results are not valid.

**Comment by wingers999** [comment]
@alex-becker-startp 

Thank you so much, that has fixed the problem for cancelled backups, and changing the results code has fixed an issue I had where not getting results if some files in use and copy couldn't complete - fantastic!!

From your use of the project what if any are the benefits of me using StartAsync rather than Start - can't see any obvious difference when trying it

Again thank you for your help and fixes

**Comment by wingers999** [comment]
@alex-becker-startp 

What are the chances that the speed figure could be reported as well?

             Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         1         0         1         0         0         0
   Files :         7         7         0         0         0         0
   Bytes :    2.56 m    2.56 m         0         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00


   **Speed :            24910925 Bytes/sec.
   Speed :            1425.414 MegaBytes/min.**
   Ended : 06 June 2018 17:39:45

**Comment by wingers999** [comment]
if you are copying a large file and click cancel it gets confused - I think somehow we need to detect if currently copying a file and then handle cancel process differently? thoughts?

**Comment by alex-becker-startp** [comment]
@wingers999 
sorry, but my time is very limited and my missing knowledge in git handling makes it very difficult for me to change things without needing a lot of time to do so.

**Comment by wingers999** [comment]
That's fine, I will see if I can work out how to do it myself, or if you do ever have time let me know, I can always help you add it to git if you just post code here

**Comment by bernatpi** [comment]
Closed. Superseded by pull request #82, that contains this commits alongside others from @wingers999 offline copy as discussed in #81.

**Comment by wingers999** [comment]
Added example usage to README.md and to RoboSharp.BackupApp

**Pull request closed without merging**
