### PR TITLE
Parsing Optimization

### LINKED ISSUE #206: parser query
@RFBomb 

Hi 

Any idea why the first one below can be parsed correctly, but the second one gives "'Source and Destination were unable to be parsed.'" error?

```
Dim a = RoboCommandParser.Parse("\\pc-01\c$\Software C:\test ""."" /E /ZB /MIR")

Dim b = RoboCommandParser.Parse("\\servername\share D:\ ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH")
```

### PR DESCRIPTION
**Pull request by RFBomb**
- Fixes #206 
 - Reworks the parser to use StringBuilder to avoid creating a potentially large amount of strings in a very short amount of time. 
 - Introduced some StringBuilder extension methods for the parser to use to manipulate it similar to a string

### CODE REVIEW

**Comment by RFBomb** [comment]
Alright, this was a lot of rework. 

High level summary:

- Reworked the RoboCommandParser to use StringBuilder for parsing instead of string parsing. This was to alleviate the potential for memory leaks that may result from generating a new string whenever a switch was extracted from the input string. 

- Consolidated RoboCommandParserFunctions into RoboCommandParser. 

- introduced StringBuilderExtensions, and did a cursory review of the library regarding for potential improvements where similar functions are used. 

- slight reorganization of some methods.

**Comment by PCAssistSoftware** [comment]
Excellent, thanks Robert, tied up with some server upgrade work now but will do some more testing of it tomorrow, as always appreciate your hard work on this

**Comment by RFBomb** [comment]
> appreciate you hard work on this

(That's why i typically only work on it on the clock lol)

I'm happy to have this merged in once you are satisfied testing it. I have some ideas to integrate this into my app, but for now have not, and just ran a few quick tests using the compiled dll dropped into my app's folder. Ran without issue, so no concern on my end. 

Once this is merged in, I'll set up another PR with the remainder of the changes I have planned regarding Regex optimizations. Didn't want to bundle these here, as this is (slightly) more targeted, and those hit more of the core library files, as well as fixing #208

**Comment by PCAssistSoftware** [comment]
> > appreciate your hard work on this
> 
> (That's why i typically only work on it on the clock lol)
> 

:)

> I'm happy to have this merged in once you are satisfied testing it. I have some ideas to integrate this into my app, but for now have not, and just ran a few quick tests using the compiled dll dropped into my app's folder. Ran without issue, so no concern on my end.

Okay will test sometime tomorrow my end and then if not problems I will get it merged in

> 
> Once this is merged in, I'll set up another PR with the remainder of the changes I have planned regarding Regex optimizations. Didn't want to bundle these here, as this is (slightly) more targeted, and those hit more of the core library files, as well as fixing #208

Excellent

**Comment by PCAssistSoftware** [comment]
Finally (after a long night of server upgrading) got round to testing this, have tested in two existing apps I use it in, tested normal processes along with parsing various different commands to ensure original reported issue relating to UNC paths was fixed, and all is working perfectly.  Will now merge as per your confirmation above :)

**Pull request merged**
