### PR TITLE
RoboSharp.Extensions Package

### PR DESCRIPTION
**Pull request by RFBomb**
This is the remainder of #161, all cleaned up ( well, it will be once I'm satisfied ).
I have been running this code in my personal project for a little over a year now, and it works great, at-least for me. I'm just cleaning it up for general consumption here. 

This Extensions package introduces various Extension Methods for the Options objects that allow evaluation of the file and directory paths in accordance with how RoboCopy evaluates them, and should achieve the same end result. 

The biggest classes to utilize here are the AbstractIRoboCommand, which has a good basis for what a custom implementation needs. Methods can be overridden to provide desired functionality. The other class to use is the PairEvaluator, which houses all of the combined logic to evaluate file and directory pairs. ( All of the other classes exist to facilitate the PairEvaluator )

### CODE REVIEW

**Comment by RFBomb** [comment]
This is very near to completion I believe!
I've got the RoboMover converted from my other project and functional here. Just need to tweak some things to get it to match the same file count/directory counts as robocopy results ( these are the failing unit tests)

**Comment by RFBomb** [comment]
Notes to self re: /compress

Requires minimum version:

https://blogs.windows.com/windowsexperience/2020/09/02/announcing-windows-server-vnext-preview-build-20206/

Simple way to test for compatibility:
Start a command with /compress and /quit. Wait for completion. If compress is allowed, it executes without error. If not allowed, it will report an unknown argument in the log/errors. 

Alternate test would be evaluating the OSVersion. But that is more Granular, and changes between .netStandard/core and .net5+

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/environment-osversion-returns-correct-version

**Comment by RFBomb** [comment]
@PCAssistSoftware 
Great news. It looks like its complete!
I brought RoboMover over from my company project, and once I started running it through the gambit of tests we had built for RoboCommand, I realized how much I missed. ( It did what I needed at the time, but wasn't fleshed out, like it is now).

DIdn't expect to spend all day on it today, but I'm quite pleased with the resulting package here. All this testing has corrected a lot of bugs that were not detected in #161. Anyone that needs to perform custom IRoboCommands should be able to do so with relative ease compared to before. 

Appveyor was being a PITA per usual though. The unit tests for RoboSharp work fine. But the unit tests for RoboSharp.Extensions that do exactly the same thing just one directory over are having Access Denied issues.

**Comment by RFBomb** [comment]
All of the RoboMover tests are bypassed on AppVeyor at the moment, as it has an issue with permissions I cannot resolve. No idea what is going on  here.

**Comment by RFBomb** [comment]
@PCAssistSoftware 
Alright, I'm very satisfied with this, other than the fact that I had to bypass all of the RoboMover tests on appveyor, which is really frustrating. All tests do execute well on my machine though.

image


Definitely try out RoboMover before you merge it in, I'd love the feedback. 
My use-case is moving files on USB2.0 devices from the root into a backup folder, and it has tremendously sped up the time required.
ex: 
root/Folder1/Folder2 -> root/USB_BACKUP/DateTime/Folder1/Folder2

**Comment by PCAssistSoftware** [comment]
@RFBomb - okay great work!!  I will take a look sometime tomorrow or Thursday when I get a moment.  Anything I need to know about how to use the new features to be able to test, or will that be obvious to me once I take a look at the code?

**Comment by RFBomb** [comment]
@PCAssistSoftware 
So for RoboMover, you simply use it just like you would a RoboCommand. If moving files on between folders on same drive, it does its own thing, otherwise it reverts back to a standard RoboCommand. 


Everything else is basically written to streamline evaluation of files/directories. So it just takes the *Options object and runs the comparison. Ex:
Result = SelectionOptions.ShouldExcludeFileName(new FilePair())

PairEvaluator condenses all of those extension methods into a single class with just a few necessary methods for a full robocopy-equivalent evaluation, making implementation of identical logic much easier if manually iterating across the directories tree. 

So the real primary classes here are:
AbstractIRoboCommand
RoboMover
ResultsBuilder
PairEvaluator

If we wanted more organization in this, most of the pure extension method providing classes could be moved into the 'Helpers' namespace. That would hide their extensions if someone were only after RoboMover for example. (This actually might be worthwhile, just leaving major classes in the root namespace)

**Comment by PCAssistSoftware** [comment]
Quick question as I am now starting to look at this - is it by choice (or for a technical reason) that the Extensions are built for net5.0, net6.0, netcoreapp3.1 and netstandard2.0  compared to RoboSharp itself which also gets built for net452 (which is what I currently use) and netstandard2.1 ?

**Comment by RFBomb** [comment]
For NetStandard2.1, the NetStandard2.0 dll would be called back into, but that's an easy add. 

For Net452, it's missing Array.Empty<>(), but I think that's it. I tried the other environments (I'm only building 2.0) but nuget kept complaining so I just ignored it and let AppVeyor run those environments lol. 

I'm gonna be resolving that on my end this morning to ensure I can build all targets now that I know the brunt of the work is done. 


Out of curiosity, why not use Net46+ ? Net452 is quite old and doesn't support .NetStandard2.0

**Comment by PCAssistSoftware** [comment]
Actually I use 4.7.2 or 4.8 in my apps, but I meant the DLL's for RoboSharp I use come from the Net452 build

**Comment by RFBomb** [comment]
This last commit has a small bit of organization done to it, and adds the support for the other targets.

**Comment by PCAssistSoftware** [comment]
Initial quick look over and it looks really good, all unit tests completing successfully my end as well.

I haven't delved into the code yet, but basically for RoboMover you are saying that if using the /MOV switch (CopyOptions.MoveFiles = True) and  source/destination on same drive it automatically switches over to using RoboMover instead of RoboCopy to do the job?

**Comment by RFBomb** [comment]
Recommended as a Merge commit due to the high volume of changes. working on the commit notes now.
Also, this would be great if once you validate it if it could be put up as a nuget package. I'm aware of the process, as I have several of my own, but I know this one has automated package uplaods and haven't set that up myself, so if you could do that sometime, that'd be fantastic.

also, before we merge this in, I want to verify my project works still, just ensuring no other changes needed here ( I don't think any changes will be needed)

**Comment by RFBomb** [comment]
> I haven't delved into the code yet, but basically for RoboMover you are saying that if using the /MOV switch (CopyOptions.MoveFiles = True) and source/destination on same drive it automatically switches over to using RoboMover instead of RoboCopy to do the job?

precisely!
If either of those are false, it will fall back to a standard RoboCommand. 
To be clear though, RoboCommand is unaffected by that logic. The custom move logic only occurs when using RoboMover.

**Comment by PCAssistSoftware** [comment]
Okay, cool - very clever.  Will get back to testing and respond to other points later - got to pop out now.

**Comment by RFBomb** [comment]
RoboSharp Changes:
- Fixed Various XML Documentation
- Authentication.cs - Prevent creating destination directory if JobOptions.PreventCopyOperation = TRUE
- CopyActionFlags 
    -  Updated Flag values as needed for proper functionality based on RoboCommand docs. 
    - Added Compress
- RoboCopyOptions
    - Added /Compress support. Note: Must have compatible RoboCopy version.
    - Added static methods to allow / test for compression being possible on your system
    - Exposed the Parse() method and added a flag to allow use within custom IRoboCommand headers
- JobFile - Fixed constructor leaving a potential null reference and issue later on- 
- JobOptions - Allow Loading a JobFile as part of the command (previously not implemented)
- ProcessedFileInfo - Correct ToString() printing
- ProgressEstimator - Improved thread safety. 
- RoboCopyResults - Added Factory Method to build from new interface IResultsBuilder
- RoboCommand - resolved various compiler naming scheme messages
- SelectionOptions
    - Exposed the Parse() method and added a flag to allow use within custom IRoboCommand headers

New Additions to RoboSharp:
- IResultsBuilder
    - This interface can be used to supply the parameters to generate a new RoboCopyResults object. Easier / more foolproof than implementing various custom constructors and methods / exposing properties.

RoboSharp.UnitTests
 - Namespace has been normalized to a more standard naming convention
 - Additional tests have been added
 - Minor changes for improved custom implementation testing


RoboSharp.Extensions
 - AbstractIRoboCommand - This class is meant to be used as a base class for custom IRoboCommands implementations.
 - CachedIEnumerable 
    - Acts as a thread-safe IEnumerable object.
    - Once it has enumerated the collection, a second iteration will be quicker as it has cached the results internally.
 - IDirectoryPair & IFilePair
    - These interfaces allow various comparison between a Source and Destination file.
    - Each of these has their own ExtensionMethods class to support those comparisons.
    - The RoboSharp.Extensions.Helpers namespace also has methods for evaluation of these objects.
 - IDirectoryPairExtensions - Provides generic methods for getting children of IDirectoryPair objects
 - IFilePairExtensions - Provides generic methods for evaluation of IFilePair objects
 - DirectoryPair - Concrete implementation of IDirectoryPair with minor optimizations built in.
 - FilePair - Concrete implementation of IFilePair
 - PairEvaluator
    - Class designed to perform all of the comparisons of IFilePair and IDirectoryPair for a custom IRoboCommand.
    - Provides various methods for filtering the collections.
    - Generates the ProcessedFileInfo objects after evaluation of the pair objects.
 - ResultsBuilder
    - Class designed to record the processing of the files/directories by a custom IRoboCommand.
    - Generates a RoboCopyResults object via the IResultsBuilder interface.
 - RoboMover & RoboMoverOptions
    - RoboMover is a custom IRoboCommand.
    - If MOVING files (CopyOptions.MoveFiles | CopyOptions.MoveFilesAndDirectories) and source/destination are on same root drive:
        - uses File.Move() to move the files. This is quicker than the Copy-delete process that RoboCopy does.
    - If the above condition is false, falls back to a standard RoboCommand.


RoboSharp.Extensions.Helpers
 - CopyOptionsExtensions & SelectionOptionsExtensions
    - These classes provide extension methods that evaluate the various options and return a result, such as if an IFilePair should be included or excluded in the operation.
 - LoggingOptionsExtensions
    - Provides methods for writing to log files based on the options configured in the LoggingOptions object
 - DirectoryRegex
    - Class that houses a regex pattern and a boolean to determine if the pattern is meant to match against DirectoryInfo.FullName or DirectoryInfo.Name
    - Used by the SelectionOptionsExtensions methods
 - IDirectoryPairEqualityComparer & IFilePairEqualityComparer
    - Generic IEqualityComparers for the interfaces. 
    - Evaluates the Source and Destination of the pairs and determine if two pair objects represent the same paths.
 - PairEqualityComparer
    - Sealed class that provides the basic IEqualityComparer<> for IFilePair and IDirectoryPair via the above classes.
 

RoboSharp.Extensions.SymbolicLinkSupport
 - Provides support for evaluation/creation of Symbolic Links

**Comment by PCAssistSoftware** [comment]
Okay, i'm back, so just a simple test of the below should move (using RoboMover) all files/folders from c:\1d to c:\2 - correct?

```
Dim job1 As New RoboMover
job1.CopyOptions.Source = "C:\1d"
job1.CopyOptions.Destination = "C:\2"
job1.CopyOptions.CopySubdirectoriesIncludingEmpty = True

job1.CopyOptions.MoveFiles = True

Await job1.StartAsync()
```

**Comment by RFBomb** [comment]
Yes.

**Comment by PCAssistSoftware** [comment]
> Yes.

That's what I thought - but it doesn't - c:\1d contains 1 file in root and then lots of files in folders / subfolders, but above ends up only moving the 1 file in root to c;\2 - nothing else

**Comment by RFBomb** [comment]
Try with CopySubdirectories = true

I might have missed that flag in IsRecursive(). 

Edit:
Ya I did.

**Comment by PCAssistSoftware** [comment]
yes confirmed working with CopySubdirectories rather than CopySubdirectoriesIncludingEmpty

**Comment by PCAssistSoftware** [comment]
> Recommended as a Merge commit due to the high volume of changes. working on the commit notes now. Also, this would be great if once you validate it if it could be put up as a nuget package. I'm aware of the process, as I have several of my own, but I know this one has automated package uplaods and haven't set that up myself, so if you could do that sometime, that'd be fantastic.

"Squash and merge" is the only option for this repository I'm afraid, "Create a merge commit" is Not enabled for this repository

image

I have no control over the NuGet side i'm afraid, all I can do is increment the version number and the automated process handles the release - so not sure how this will work with the Extensions Package.  Maybe something we will have to ask Terry to do once we have validated and merged it.

**Comment by RFBomb** [comment]
I meant squash and merge!

I'm sure you saw the rather large summary I wrote up for when that occurs. 

At the moment, I'm working the kinks out of the purging and depth systems. The way I use the command doesn't have a need for it, so I never tested it. And hoo boy is it another level of complexity. But if it's gonna get released into the wild, I want to cover that base.

**Comment by PCAssistSoftware** [comment]
> I meant squash and merge!

oh cool, that's okay then - I don't tend to do anything else usually

> I'm sure you saw the rather large summary I wrote up for when that occurs.

yes , perfect thanks

> At the moment, I'm working the kinks out of the purging and depth systems. The way I use the command doesn't have a need for it, so I never tested it. And hoo boy is it another level of complexity. But if it's gonna get released into the wild, I want to cover that base.

agreed.  Been playing with it some more this evening and you have done a fantastic job with this package!

**Comment by RFBomb** [comment]
Note for implementation of the process order (need to rework):

- Extra Directories ( /purge /x ) - need to write a method for this for ease of coding
- Extra Files ( /purge /x /v ) - write a method for this as well 
- All other files
- All other directories


Retries are not implemented at all. (If requested I can do this, but may not be needed)


So current rework proposal:
- new method for handling extra sub-dirs that have been discovered. 
- new method for handling extra files. 
- enumerate all directories within current dir pair. Filter by IsExtra(). 
- enumerate all files within current dir pair. Filter by IsExtra()

- create two new helper classes:
--- DirPairCollection & FilePairCollection

These will have following properties:
- Collection (input collection)
- Extras (any that are IsExtra)
- Remaining

**Comment by RFBomb** [comment]
More tests have been written. 
Some messy logic has been added.
But it now passes 82 different tests that compare itself to robocopy.

There was a nightmare edge case involving the file filter changing extra file and directory reporting behavior that was causing it to fail, which i believe I have resolved, if the test is adequate.

**Comment by RFBomb** [comment]
Ok, I plan to modify one of the tests to provide that files are actually moved and purged from the destination, as opposed to all the current tests that basically just look at the results objects and no further validation. 

Then I'll bring it into my project to double check. 
Once that's satisfied, I'm happy to have it merge. I think it'll be smooth from here. 

If Terry can't/doesn't want to upload it as a package, I can do so.

**Comment by PCAssistSoftware** [comment]
Excellent, let me know when done, I will do final testing and merge it in, and then contact Terry

**Comment by RFBomb** [comment]
Ok, as I said I think I'm quite satisfied here.  I fear if I continue working on this it will exceed planned scope. 

I have another IRoboCommand built and pretty much ready to publish, but I feel as if adding it in here exceeds the scope of the original intent, which was to provide the base methods for custom implementations, not necessarily provide multiple. 

The issue with  bringing in the other one is that it involves several additional interfaces, several additional classes, and manually invoking CopyFileEx via a [DllImport] methods. to perform the copy/move operations. (Getting feedback directly from the system instead of feedback from robocopy). It works well, and I've been using it in my program for about a year+ now. But I think adding it in addition to all this stuff may be too cumbersome.  ( Its quite neat, its effectively an IROboCommand that you provide any file path to and it adds it to a queue, so it doesn't dig through directories but can copy as many disparate paths as you submit)

image

**Comment by PCAssistSoftware** [comment]
Had been testing this afternoon ready for you, so just tested again with your last commits and all seems okay.  

My only complaint and this is unrelated really as has nothing to do with your code as it happens with standard RoboCopy is that when moving folders from one location to another it always seems to leave the empty folder structure in the source location rather than getting rid of them!

Anyway that's not relevant and just a personal annoyance :)

Perhaps you could increment the version number to 1.3.1 for both RoboSharp and RoboSharp.Extensions projects so when I merge we get a new NuGet package for at least NuGet, and then if it doesn't automatically create one for the Extensions (not sure how Terry has it configured), I can then get in touch with him about doing so.

**Comment by PCAssistSoftware** [comment]
P.S. Meant to say I like the sound of your other IRoboCommand, agree perhaps too much to include here for now, but would like to take a look at it sometime.

**Comment by RFBomb** [comment]
I can increment. 
MoveFilesAndDirectories should resolve that.

I'll try to test that on Monday and do the increment then.

**Comment by PCAssistSoftware** [comment]
> MoveFilesAndDirectories should resolve that.

DOH, didn't think of that, was just using MoveFiles!!

Now tested both RoboCommand and RoboMover with MoveFilesAndDirectories and it worked fine :)

**Comment by RFBomb** [comment]
Alright @PCAssistSoftware 
I've worked out any kinks by re-integrating these changes into my custom implementations to validate them, and got those building just fine. I've reworked the test to validate that files are in fact getting purged and moved properly (by testing file existence as opposed to just testing results counts). I've stripped out any of the extra items I mentioned in my earlier comment that would exceed the required scope here. 

And the Version# is incremented. I feel like this is ready.

**Comment by PCAssistSoftware** [comment]
Cool, will do one final test tomorrow with latest changes and then I will do the squash and merge!!

**Comment by PCAssistSoftware** [comment]
@tjscience - Terry, as you can see from this PR Robert (@RFBomb) has created an excellent Extensions namespace for RoboSharp which adds some extra functionality (covered in more detail [here](https://github.com/tjscience/RoboSharp/pull/181#issuecomment-1746992532) - is there any chance this could also be added to NuGet as a separate package?

**Comment by tjscience** [comment]
> @tjscience - Terry, as you can see from this PR Robert (@RFBomb) has created an excellent Extensions namespace for RoboSharp which adds some extra functionality (covered in more detail [here](https://github.com/tjscience/RoboSharp/pull/181#issuecomment-1746992532) - is there any chance this could also be added to NuGet as a separate package?

Wow, really great work @RFBomb! I would guess that you put a lot of time and effort into this and it looks great. Thank you guys (and all other contributors) for keeping this project alive. I appreciate it a lot and love that it is still being used to benefit devs.

Publishing the extension project to nuget is a great idea. Let me figure out how I can do that with appveyor so that it is seamless and works the same way RoboSharp nuget is published. I will try to get back to you guys soon. Thanks again!

**Comment by RFBomb** [comment]
@tjscience Thanks, glad you could get a chance to review it. 

This was born out of necessity. The application I'm creating synchronizes data from some server locations on a network down the the user's local pc to offline caching. The sync framework I wrote is utilizing RoboSharp as its back-end for doing the data transfers. Robosharp made it very easy to do what it needed. But I found that as it grew in complexity, I needed/wanted to implement some custom IRoboCommands. I started off by creating RoboQueue, which eventually became my SyncedCopyQueue. And moving files on USB2.0 was attrociously slow, so RoboMover (included in this package) was born to greatly speed up the execution time there. With how great the initial package was, and that I'm on the clock developing this other project, I'm more than happy to contribute those developments here.

**Pull request merged**
