### PR TITLE
IFileCopier Test Improvement

### PR DESCRIPTION
**Pull request by RFBomb**
Adds a test and corrects the issue noted in #211 to ensure that the copy operation is performed correctly.

### CODE REVIEW

**Comment by RFBomb** [comment]
Interestingly, the issue comes from the optimization Visual Studio recomended for .Net5+, using `Memory<byte>` in place of `byte[]`....  The Net472 tests do not error, while Net5 and Net8 do....

**Comment by PCAssistSoftware** [comment]
> Interestingly, the issue comes from the optimization Visual Studio recomended for .Net5+, using `Memory<byte>` in place of `byte[]`.... The Net472 tests do not error, while Net5 and Net8 do....

Great work in tracking down the cause.  Happy to get it merged in now for you if ready.

**Comment by RFBomb** [comment]
Its not ready! Also, this didn't run appveyor?

**Comment by PCAssistSoftware** [comment]
okay, sorry, not sure why, will check settings

**Comment by PCAssistSoftware** [comment]
Project has been transferred over to me from tjscience so possibly a missing setting in appveyor since the transfer, I will check.

Project marked as draft for now so I don't try and jump the gun :)

UPDATE: hopefully resolved now

**Comment by RFBomb** [comment]
This last commit resolves the copy operation and attributes issue, should be good to merge!

**Comment by PCAssistSoftware** [comment]
Okay, will do it shortly then.  Looks like AppVeyor now running okay as well.

**Comment by RFBomb** [comment]
Woops, forgot to update the version number, one sec

**Comment by RFBomb** [comment]
I haven't seen Extensions v1.6.1 pop up into nuget yet, I think that was previously automated as well. May have to look into that or upload manually. No rush on that though, i'm not back on project ill Jan 2nd lol

**Comment by PCAssistSoftware** [comment]
I got an email confirming it had been published so should all be working okay. 

UPDATE: checked and showing okay on Nuget site

image

**Comment by RFBomb** [comment]
your correct, I was looking at the base package ><
This also resolve my project's unit test!

**Pull request merged**
