### PR TITLE
Fix43_Truncated - Needs Verification before Merge

### PR DESCRIPTION
**Pull request by RFBomb**
My update of Fix43 required the changes performed in #107. but since that was a convoluted mess due to the PR's within #107, that became pretty attrocious to read.

Since 107 was merged into the dev branch, this is a new branch showing only the changes proposed for Fix43, based off a fresh clone of the main branch.

This Supercedes #108 (closed) and #45 (by incorporating #45's changes into the latest dev branch).

### CODE REVIEW

**Comment by PCAssistSoftware** [comment]
Excellent, thanks Robert

**Comment by PCAssistSoftware** [comment]
Just completed testing this fix in a domain environment - copying data to a destination location which required specific credentials and it worked perfectly fine.  Repeated test supplying incorrect credentials and NO credentials to confirm it is working correctly.

Thanks again Robert (@RFBomb).

Will merge it shortly.

**Comment by RFBomb** [comment]
Just to confirm, this didn't have any effect on local copies where no credentials are passed?
I'm effectively passing in String.empty for those credential values in my setup, because most copies are from local to USB or vice versa

**Comment by PCAssistSoftware** [comment]
No it didn't have any effect at all on local copies when passing no credentials :)

**Comment by PCAssistSoftware** [comment]
Update: just to be sure I have run some more local copies from one internal drive to another and to / from USB, some small copies, some very large.  And when just doing .Start() with no credentials as all it works perfectly fine.

**Comment by RFBomb** [comment]
Awesome, thanks for proving it out.

**Pull request merged**
