### PR TITLE
Add new target framework: .Net 6.0

### PR DESCRIPTION
**Pull request by gabrielgt**
- Added target framework .Net 6.0 with support for authentication, using WindowsIdentity.RunImpersonated API, which is not supported on netstandard2.1.
- Updated target framework from .Net Framework 4.5 to 4.5.2. Developer pack for 4.5 is not longer available (https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?cid=getdotnetsdk).
- Added PlatformNotSupportedException when trying to use authentication on unsupported target frameworks.
- Solves issue #162.

### CODE REVIEW

**Comment by PCAssistSoftware** [comment]
Thanks, sorry for delay - has been partially implemented with #174 - I need more time to fully test the authentication changes and then I will merge those as well

**Comment by PCAssistSoftware** [comment]
@gabrielgt - if you can update your dev to the latest version  of dev from this repository (several changes have been made since this pull request was made) so PR is up-to-date then I can test the authentication changes and get it merged this week for you.  At the moment I can't easily test it as downloading the PR in GitHub desktop is reversing the changes I had made to dev yesterday and last commit - thank you

**Comment by PCAssistSoftware** [comment]
@gabrielgt - please can you update your dev branch so it is in sync with https://github.com/tjscience/RoboSharp/tree/dev so PR is up-to-date then I can test the authentication changes and get it merged this week for you. At the moment I can't easily test it as downloading the PR in GitHub desktop is reversing the changes I had made to dev recently in last commit - thank you

**Comment by PCAssistSoftware** [comment]
thanks @gabrielgt - will take a look in the next few days

**Comment by gabrielgt** [comment]
@PCAssistSoftware - Done!👍

**Comment by PCAssistSoftware** [comment]
Tested this evening with .NET 4.8 and .NET 6.0 and authentication support working fine - happy to merge

**Pull request merged**
