### PR TITLE
New dev base for wingers and bernatpi to work on

### PR DESCRIPTION
**Pull request by wingers999**
History notes:-

20/09/18 - this fork combines the 1.20 release from tjscience with the results code from alex-becker-startp (https://github.com/alex-becker-startp/RoboSharp/tree/new/copyResults) - N.B. This was pull request #40 but some fixes didn't make pull so got all changes from above fork

21/09/18 - made changes to RetryOptions.cs for default retryCount and retryWaitTime - made changes in CopyOptions.cs to remove default copyFlags and directoryCopyFlags - finally added new isCancelled boolean to RoboCommand.cs

21/09/18 - removed .NET 4 support from RoboSharp.csproj as code for creating results requires 4.5

15/02/20 - this also includes changes in pull requests 68 and 80 - https://github.com/tjscience/RoboSharp/pull/68 / https://github.com/tjscience/RoboSharp/pull/80

### CODE REVIEW

**Comment by bernatpi** [comment]
Hi @wingers999. I've pulled changes and resolved merge conflicts from the current `dev` in order to start working with an updated version. It's working on my end, but can you please check on yours? Thank you

**Comment by wingers999** [comment]
Looking good here - do we have to then click Squash and merge for it to merge the changes?

**Comment by bernatpi** [comment]
I think it's not ready to merge. I've pulled changes from the main `dev` but I haven't sorted the cancellation issue or implemented the speed results, so there's work yet to do. I prefer to wait until this issues are sorted out and then merge this pull request with the main `dev`. Does that sound correct?

**Comment by wingers999** [comment]
yes that makes perfect sense to me

**Comment by bernatpi** [comment]
@wingers999 I've added the speed results to the ´RoboCopyResults´ object. `results.SpeedStatistic.ToString()` should return the two lines that robocopy shows to the user. Mind that you should check `results.SpeedStatistic` for `null` because robocopy does not always provide this results.

**Comment by wingers999** [comment]
@bernatpi - excellent work, just tested the speed stats and works well for me

**Comment by wingers999** [comment]
@bernatpi - excellent work, just tested the speed stats and works well for me

**Comment by bernatpi** [comment]
Quote from #40:

> if you are copying a large file and click cancel it gets confused - I think somehow we need to detect if currently copying a file and then handle cancel process differently? thoughts?

I could not reproduce the error. In what way it gets confused? When I click the cancel button the App just stops the copying process.

**Comment by wingers999** [comment]
@bernatpi - my original reporting of that issue was from 18 months ago and I can't remember off hand the details, but I have just tried it again now and it seems to work fine, so perhaps some later changes had already resolved the issue.  We can always come back to it later if I can recreate at any point, but hopefully not.

**Comment by bernatpi** [comment]
@wingers999 Yes, that makes sense, we can always open an issue later. So... tomorrow I will take another look at the `SpeedStatistic`, mainly to try different languages and make sure that the parsing works on every case. Now I _think_ it works, but it's better to be sure :P

**Comment by wingers999** [comment]
@bernatpi - I will keep following your changes and test when you need me to, but excellent progress so far :)

**Comment by alex-becker-startp** [comment]
@wingers999 - hey, great that you found a way to merge the statistics changes, so I can finally switch back to the nuget release soon.

@bernatpi  - the statistics parsing is not language dependent. 
But the error parsing is, which is why I added the RoboSharpConfiguration.ErrorToken property.
It will work for en-XX and de-XX languages out of the box.
For other languages the property has to be set to the languages dependent error string.

**Comment by bernatpi** [comment]
@alex-becker-startp - Thanks you for your clarifications, and, well, for the statistics in general. There's great work in there. For the language dependence I was refering mostly to the `SpeedStatistic` that I implemented yesterday, because I don't know if robocopy changes the format of the output depending on the current culture (`.` or `,` for decimal separator, and so on) and this implementation does not account for any of that.

**Comment by alex-becker-startp** [comment]
@bernatpi - ah, I see. Feel free to peek into `Statistics.cs ParseTokenString()` method. This code deals with the number format culture differences.
btw: where can I find the `SpeedStatistic` class? I took a look into your fork, but did not find it.

**Comment by bernatpi** [comment]
@alex-becker-startp - Thanks, I will take a look at that.

I implemented the `SpeedStatistics` class directly on this pull request (commit 3e503f47) in order to ease the merge with the main `dev` branch. Please feel free to add reviews and/or change the code.

**Comment by alex-becker-startp** [comment]
@bernatpi - improvement suggestions

I've reviewed your implemention and suggest the following changes:
 - `ResultsBuilder.cs:39 if (statisticLines.Count >= 6)` as you only refer to lines 5 and 6 (index [4] and [5])
 - `SpeedStatistic.cs:27` change regex pattern to `\d+([\.,]\d+)?` which includes numbers with comma or decimal separator and without fractions
 - `SpeedStatistic.cs:33 and :39` change `match.Value` to `match.Value.Replace(',', '.')` to support parsed commas as decimals.

Nice work, hope to see it on nuget release soon !

**Comment by bernatpi** [comment]
@alex-becker-startp - Thanks! Changes implemented at 399617c.

Given that @alex-becker-startp's input solves the language issue, I think this is ready to merge to the base `dev` branch.

**Comment by wingers999** [comment]
I agree - great work!, now popping out but when back and merged I will do some testing etc

**Pull request merged**
