### PR TITLE
Fix #178

### LINKED ISSUE #178: RoboCommand Dispose code wrong
We currently experience following exception in finalization code of RoboCommand:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at RoboSharp.RoboCommand.get_IsScheduled()
   at RoboSharp.RoboCommand.Dispose(Boolean disposing)
   at RoboSharp.RoboCommand.Finalize())
```
And looks like RoboCommand dispose is malformed. There is no check for disposing flag https://github.com/tjscience/RoboSharp/blob/dev/RoboSharp/RoboCommand.cs#L891

### PR DESCRIPTION
**Pull request by RFBomb**
- Modifies IsScheduled evaluation to avoid evaluation the CopyOptions object, which may have already been collected
- Added a IsWindowsPlatform field to VersionManager. Wrote in various checks for this to throw PlatformNotSupported exceptions for non-windows platforms as needed.
- Rewrote some logic to use newer .Net6 functionality instead of using DLL Imports that are windows only. 
- Fix RoboCommandParser failing to parse when submitted with quoted empty paths for source/destination

### CODE REVIEW

**Comment by PCAssistSoftware** [comment]
@RFBomb - are you happy for this one to get merged in or would you rather wait until @zabulus tests it and responds?

Perhaps we should increment version on this one, and I will then merge it after I merge #198

**Comment by RFBomb** [comment]
Ideally wait until we get a response from a Linux test. But our tests are checking out fine so I'm ok with it.

**Comment by PCAssistSoftware** [comment]
Okay I will give it a few more days to see if he responds then

**Comment by PCAssistSoftware** [comment]
Thought I would have a go at testing in Linux, so have installed a ubuntu virtual machine, and have tried to create a .NET core console app I can use for testing, but for whatever reason I can't even get it to run under windows let alone try under linux.

I don't tend to use .NET core or console apps usually so not sure what I have missed, but get status of waiting for activation.


image

**Comment by RFBomb** [comment]
you have the right idea. but you need to await the Start() command, otherwise you exit the console app before robocopy finishes.
here is a quick .net6 console app I set up, I can commit to the repo if you like.


```
using RoboSharp;
using RoboSharp.Interfaces;
using System.Threading;
using System.Threading.Tasks;

// This example console app uses Top-Level Statements introduced in .Net6, hence no need for a 'Program' class with a 'Main' routine.

// See https://aka.ms/new-console-template for more information

IRoboCommandFactory commandFactory = RoboCommandFactory.Default; // Change this to the desired factory - a custom factory will be required for use with linux systems


IRoboCommand cmd = AskForCommandParameters(commandFactory);

cmd.OnFileProcessed += Cmd_OnFileProcessed;
cmd.OnError += Cmd_OnError;

try
{
    await cmd.Start();
}
catch(Exception e)
{
    Console.WriteLine(e.Message);
    Console.ReadLine();
    System.Environment.Exit(1);
}
System.Environment.Exit(0);


static IRoboCommand AskForCommandParameters(IRoboCommandFactory factory)
{
    while (true)
    {
        try
        {
            Console.WriteLine("Enter your Robocopy text to be parsed: ");
            string input = Console.ReadLine();
            IRoboCommand command = RoboSharp.RoboCommandParser.Parse(input, factory);
            return command;
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
    }
}

static void Cmd_OnFileProcessed(IRoboCommand sender, FileProcessedEventArgs e)
{
    Console.WriteLine(e.ProcessedFile.ToString());
}

static void Cmd_OnError(IRoboCommand sender, RoboSharp.ErrorEventArgs e)
{
    Console.WriteLine(e.Error);
}
```

**Comment by PCAssistSoftware** [comment]
Yes I had tried it with Await but then couldn't build as got "BC30737	No accessible 'Main' method with an appropriate signature was found in 'ConsoleApp1'.".  So at that point I tried it without.  Make sense though.

If you stick it somewhere on your github repo so I can download it, then I will see if I can do the testing in my Linux VM for us.

**Comment by RFBomb** [comment]
you would have to mark your Main() method as asynchronous. Not sure how thats done in VB.
anyway, i committed my super-basic console app. you can either write a command and execute it like any other console app with command arguments or you can start it up and it will ask for a robocopy parameter string

for example:

`Robosharp.consoleapp.exe robocopy someSource someDestination /L` will execute robocopy just like it would off of the native console

**Comment by RFBomb** [comment]
Now for what it's worth, this is a very basic console app. When I compiled it, it compiled into an exe. Not sure how to run it in a Linux environment. I believe it has to be recompiled for Linux. So the code as is should work, if you can figure out how to get it to compile.

**Comment by PCAssistSoftware** [comment]
I have your console app working fine in Windows, so I will try on Linux tomorrow - getting late here now (01:37) so will report back tomorrow :)

**Comment by PCAssistSoftware** [comment]
Good morning, in the end I used my Raspberry Pi which is setup to run .NET as had problems with the ubuntu VM.

Hopefully screenshot below confirms it is working as intended?  If you need me to test anything else under Linux just let me know :)

linux_robosharp

**Comment by RFBomb** [comment]
That is working as intended!
This means it successfully initializes everything, and only fails on the Start() command. 

If you go into the console app, remove the project references for Extensions and RoboSharp, and instead use the currently available nuget package, I would suspect you can get the same error reported in the initial issue post.

**Comment by PCAssistSoftware** [comment]
Running with nuget package:

linux_robosharp2

**Comment by RFBomb** [comment]
That's exactly what I expected to see. So it looks like the changes here work. I'm ok with merging. 

As an aside to these changes, what I'm working on over in that draft request is a more flashed out version of a custom implementation. 

I intend to add two more implementations along side of the Robomover class that already exists. One implementation will be Basically a Queue of files and destinations to copy. The other one will be a clone of Robocopy itself, which would technically enable support for this library on Linux  that mimics the actual Robocopy executable.

**Comment by RFBomb** [comment]
Wait! This technically doesn't dispose. So that should tests. Give me a moment to update.

**Comment by PCAssistSoftware** [comment]
> That's exactly what I expected to see. So it looks like the changes here work. I'm ok with merging.

Will wait for your update as per previous post.   When ready could you also increment the version please.

> As an aside to these changes, what I'm working on over in that draft request is a more flashed out version of a custom implementation.
> 
> I intend to add two more implementations along side of the Robomover class that already exists. One implementation will be Basically a Queue of files and destinations to copy. The other one will be a clone of Robocopy itself, which would technically enable support for this library on Linux that mimics the actual Robocopy executable.

Excellent - that all sounds really good

**Comment by RFBomb** [comment]
Ok, the changes should work now. 

If using old nuget package it should cause the same disposal issue described in the issue post in a non-windows environment, But should work fine if using the project reference that has the new code. And should have no issues in a windows environment.

**Comment by PCAssistSoftware** [comment]
> Ok, the changes should work now.
> 
> If using old nuget package it should cause the same disposal issue described in the issue post in a non-windows environment, But should work fine if using the project reference that has the new code. And should have no issues in a windows environment.

Trying to test but can't build the console app after changes get error on line 32 

image

**Comment by RFBomb** [comment]
Yea I realized that when the test failed (committing from my phone). I didn't realize IRobocommand doesn't inherit IDisposable.

**Comment by PCAssistSoftware** [comment]
> Yea I realized that when the test failed (committing from my phone). I didn't realize IRobocommand doesn't inherit IDisposable.

No probs.

Anything you want me to specifically test before merging?

**Comment by RFBomb** [comment]
Just retest the before/after changes in the Linux environment again. The new console app should report the unsupported exception when using the project reference and should produce the disposal error when using the nuget package. 

This should be complete, I don't anticipate it differing from the screenshots you posted earlier (other than I slightly changed the wording on the start exception)

**Comment by PCAssistSoftware** [comment]
> Just retest the before/after changes in the Linux environment again. The new console app should report the unsupported exception when using the project reference and should produce the disposal error when using the nuget package.
> 
> This should be complete, I don't anticipate it differing from the screenshots you posted earlier (other than I slightly changed the wording on the start exception)

tests complete, as expected using nuget just shows the same as before, using PR build shows as below

linux_robosharp3

**Comment by PCAssistSoftware** [comment]
Just confirming happy for me to merge and I will do it now

**Comment by RFBomb** [comment]
Yes merge away

**Comment by PCAssistSoftware** [comment]
> Yes merge away

Will do it now.  As a side note I will keep my linux test environment handy in case you need me to test anything else under linux.

**Pull request merged**
