### PR TITLE
Introduce Interfaces, Restructure Files, Some Optimizations

### PR DESCRIPTION
**Pull request by RFBomb**
This is PR is comprised of the numerous changes made while developing #128, but without RoboQueue specific items. 
My goal with this PR is to bring in all the bug fixes, tweaks, improvements, and structure changes prior to creating the PR for #128.

This PR is also what I feel should be the last commit for Net40 support, as laid out in #136.

Essentially what I did was copy my RoboQueue folder in its entirety, create a new branch based off the current Dev branch, then overwrite all files with the files from RoboQueue. I then went through each file and created commits to showcase how each file changed, so that the individual changes can be viewed and compared. 

What this encompasses:
- Moved all EventArgs objects out of the main folder / parent classes and into a new folder for Event Args. I named it EventArgObjects to avoid autogenerated files being `RoboSharp.EventArgs` namespace, which wipes out the ability to call up the `EventArgs` class.
- Moved all Interfaces I created and commited previously out of their parent class's files and into the Interface folder where they should have been originally. (Woops)
- Some EventArgs have been introduced.
- BugFixes and Optimizations have been made on various files, the largest of which was the Statistics file.

I tried to contain the changes for each file within just a few commits that can be reviewed (and described) individually to allow them to showcase each change.

### CODE REVIEW

**Comment by PCAssistSoftware** [comment]
Excellent work , let me know if you want me to merge this now or later?

**Comment by RFBomb** [comment]
Hold off on the merge for now, I want to verify that @tjscience  is fine with the moving the EventArgs and give him a chance to review.

**Comment by PCAssistSoftware** [comment]
Okay, that's fine

**Comment by tjscience** [comment]
Hi guys. Everything looks really good here. Thanks again @RFBomb for all of your work here. I am also in favor of splitting off a last release and nuget package for .NET4.0. We actually did the same thing for .NET3.5 awhile back, so this will be consistent.

**Comment by RFBomb** [comment]
OK, I just went poking through the issue lists seeing if there was anything else worth messing with, including #105 (which I don't see why its an issue if threads are idle, but can understand the desire for the request, just don't know enough about it to even think about such a change). 

I put in the recomendation from #103 that was suggested also as a fix for #83. It is in the configuration class now, so by default it will use system language, but can be set null if a consumer needs it. (Previous functionality it was never set, so it remained null)

This should introduce the multi-language support there, and with the other changes made to this class, expanding language support should be doable should someone need to.

I;ve done some test copies, and since this fix is also what Joe did in #103  for german language support, I believe it should be fine.

As far as I am concerned, this is mergable. I've only left RoboQueue specific items out of this PR.

**Comment by PCAssistSoftware** [comment]
Okay, happy to merge it for you now if ready?

**Comment by RFBomb** [comment]
Yes, this is ready for merge. I'll start prepping RoboQueue actual PR once I merge this into that

**Pull request merged**
